# Pre-commit hooks configuration for Belay.NET
# See https://pre-commit.com for more information

repos:
  # General linting and formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'  # Don't remove trailing spaces from markdown (needed for line breaks)
      - id: end-of-file-fixer
      - id: check-yaml
        name: Validate YAML files
        description: Checks yaml files for parseable syntax
        files: \.(yaml|yml)$
        exclude: micropython/  # Exclude micropython submodule
      - id: check-json
        name: Validate JSON files
        exclude: micropython/  # Exclude micropython submodule
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']  # Limit files to 1MB
      - id: mixed-line-ending
        args: ['--fix=lf']  # Force LF line endings

  # GitHub Actions workflow validation
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint
        name: Validate GitHub Actions workflows
        files: ^\.github/workflows/.*\.ya?ml$
        
  # .NET specific hooks
  - repo: https://github.com/dotnet/format
    rev: v5.1.250801
    hooks:
      - id: dotnet-format
        name: Format C# code
        entry: dotnet format
        language: system
        files: \.(cs|csproj|sln)$
        pass_filenames: false
        args: ['--include', '.']
        exclude: micropython/  # Exclude micropython submodule

  # Documentation validation (custom)
  - repo: local
    hooks:
      - id: validate-documentation
        name: Validate documentation build
        entry: scripts/validate-docs.sh
        language: script
        files: ^docs/.*\.(md|vue|ts|js|json)$
        pass_filenames: false
        stages: [commit]
        
      - id: yaml-syntax-check
        name: Advanced YAML syntax validation
        entry: python3 -c "import yaml; import sys; [yaml.safe_load(open(f)) for f in sys.argv[1:]]"
        language: system
        files: \.(yaml|yml)$
        exclude: micropython/  # Exclude micropython submodule

# Configuration
default_language_version:
  python: python3
  
fail_fast: false  # Run all hooks even if some fail

# Exclude patterns
exclude: |
  (?x)^(
    micropython/.*|
    \.vitepress/dist/.*|
    node_modules/.*|
    bin/.*|
    obj/.*
  )$