name: Release to NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build core packages only
      run: |
        dotnet build src/Belay.Attributes/Belay.Attributes.csproj --configuration Release --no-restore
        dotnet build src/Belay.Core/Belay.Core.csproj --configuration Release --no-restore
    
    - name: Create NuGet packages
      run: |
        dotnet pack src/Belay.Core/Belay.Core.csproj --configuration Release --no-build --output ./packages
        dotnet pack src/Belay.Attributes/Belay.Attributes.csproj --configuration Release --no-build --output ./packages
    
    - name: Publish to NuGet
      run: |
        echo "Publishing Belay.Core package..."
        dotnet nuget push "packages/Belay.Core.*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
        echo "Publishing Belay.Attributes package..."
        dotnet nuget push "packages/Belay.Attributes.*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    
    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: packages/*.nupkg